---
# File: node.yml
# Part: nodejs
#
# Description: Installs nodejs from source
#
# Parameters - Must be definied in playbook:
#   - node.path = The nodejs path
#   - node.prefix = The prefix
#   - node.tarball = The tarball filename at nodejs.org
#   - node.version = The wanted version of node to be installed

- name: init | Give permissions to .bashrc
  shell: chown vagrant:vagrant /home/vagrant/.bashrc
  tags:
    - init
    - common

- name: Node.js | Download and run nvm install script
  shell: curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.26.1/install.sh | bash
  sudo: yes
  sudo_user: vagrant
  tags:
    - nvm
    - nodejs
    - common

- name: Node.js | Install nodejs version
  shell: export NVM_DIR="/home/vagrant/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" && nvm install {{node.version}}
  sudo: yes
  sudo_user: vagrant
  tags:
    - nvm
    - nodejs
    - common

- name: Node.js | Set default alias
  shell: export NVM_DIR="/home/vagrant/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" && nvm alias default {{node.version}}
  sudo: yes
  sudo_user: vagrant
  tags:
    - nvm
    - nodejs
    - common

- name: Node.js | Use nodejs engine
  sudo: yes
  sudo_user: vagrant
  shell:  export NVM_DIR="/home/vagrant/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" && nvm use default
  tags:
    - nvm
    - nodejs
    - common
