---
- name: npm packages | Install npm packages
  shell: export NVM_DIR="/home/vagrant/.nvm" && [ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" && nvm use default && npm -g install {{ item }}
  with_items: npm_packages
  tags:
    - npm_packages
    - common
