---


- name: zendframework | Install zend framework
  shell: rm -rf /usr/local/src/zf1 && git clone https://github.com/zendframework/zf1.git /usr/local/src/zf1
  tags: 
    - zendframework
    - common

- name: zendframework | update zf1
  shell: git pull
  args:
    chdir: /usr/local/src/zf1
  tags: 
    - zendframework
    - common

- name: zendframework | link zf1 into include_path
  shell: ln -s /usr/local/src/zf1/library/Zend /usr/share/php/Zend creates=/usr/share/php/Zend/Version.php
  tags: 
    - zendframework
    - common

- name: klear | Generate storage folder
  command: mkdir -p /vagrant/web/storage creates=/vagrant/web/storage
  ignore_errors: yes
  sudo: yes
  sudo_user: vagrant
  tags:
    - zendframework
    - storage
    - common

- name: klear | Change permisions of storage folder
  command: chmod -R 777 /vagrant/web/storage
  ignore_errors: yes
  tags:
    - zendframework
    - storage
    - common

- name: klear | Generate cache folder
  command: mkdir -p {{ application_path }}/cache/ creates={{ application_path }}/cache/
  ignore_errors: yes
  sudo: yes
  sudo_user: vagrant
  tags:
    - zendframework
    - cache
    - common

- name: klear | Change permisions of cache folder
  shell: chmod -R 777  {{ application_path }}/cache/
  tags:
    - zendframework
    - cache
    - common
