---

- hosts: all
  sudo: true
  vars_files:
    - vars/main.yml
    - vars/php.yml
    - vars/phing.yml
    - vars/gearmand.yml
    - vars/node.yml
    - vars/ruby.yml    
    - vars/redis.yml
    - vars/elasticsearch.yml
    - vars/kibana.yml
    - vars/logstash.yml
    - vars/filebeat.yml
  handlers:
    - include: handlers/handlers.yml
  tasks:
    - include: fixedTasks/init.yml
    - include: roles/009-klear_backend_with_Angular_Frontend.yml
