---
- name: restart apache
  shell: /etc/init.d/apache2 restart

- name: reload apache
  shell: /etc/init.d/apache2 reload

- name: restart mysql
  shell: /etc/init.d/mysql restart

- name: restart gearmand
  shell: /etc/init.d/gearmand restart

- name: restart gearmandpersistent
  shell: /etc/init.d/gearmandpersistent restart

- name: restart supervisor
  shell: sudo /etc/init.d/supervisor stop && sleep 1 && sudo /etc/init.d/supervisor start

- name: set timezone
  shell: export TZ={{ timezone }}

- name: start syslog
  shell: service inetutils-syslogd start

- name: start postfix
  service: name=postfix state=restarted
  ignore_errors: yes
  
- name: restart postfix
  service: name=postfix state=restarted
  
- name: Restart Elasticsearch
  service: name=elasticsearch state=restarted
  
- name: Restart Kibana
  service: name=kibana state=restarted
  
- name: restart logstash
  service: name=logstash 
           state=restarted 
           enabled=yes
           
- name: restart filebeat
  service:
    name: filebeat
    state: restarted
    
- name: restart redis_6379
  shell: /etc/init.d/redis_6379 restart
  
- name: restart redis-server
  shell: /etc/init.d/redis-server restart
  
- name: restrat cron
  shell: /etc/init.d/cron restart