---
- name: restart apache
  shell: /etc/init.d/apache2 restart

- name: reload apache
  shell: /etc/init.d/apache2 reload

- name: restart mysql
  shell: /etc/init.d/mysql restart

- name: restart gearmand
  shell: /etc/init.d/gearmand restart

- name: restart gearmandpersistent
  shell: /etc/init.d/gearmandpersistent restart

- name: restart supervisor
  shell: sudo /etc/init.d/supervisor stop && sleep 1 && sudo /etc/init.d/supervisor start

- name: set timezone
  shell: export TZ={{ timezone }}

- name: start syslog
  shell: service inetutils-syslogd start

- name: start postfix
  service: name=postfix state=started
  
- name: restart postfix
  service: name=postfix state=restarted
  
- name: restart inetutils-syslogd
  service: name=inetutils-syslogd state=started